sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with Dockerfile"
  - docker build -t sg20180546/docker-nginx-travis -f react-docker/Dockerfile.dev .

script:
  - docker run -e CI=true sg20180546/docker-nginx-travis npm run test -- --coverage

after_success:
  - echo "Test Success"