version: '3'

services:
  frontend: 
    image: sg20180546/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: sg20180546/docker-nginx
    ports:
      - "80:3500"
    mem_limit: 128m
    links:
      - frontend
      - backend
  
  backend:
    image: sg20180546/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST : getlog2.cnio27em9obt.us-east-1.rds.amazonaws.com
      MYSQL_USER : root
      MYSQL_ROOT_PASSWORD: asdf3179
      MYSQL_PORT: 3306
      MYSQL_DATABASE: myapple
    mem_limit: 128m