sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with Dockerfile"
  - docker build -t sg20180546/docker-nginx-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true sg20180546/docker-nginx-travis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker-app"
  env: "Reactdockerapp-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-830503619726"
  bucket_path: "react-docker-app"
  on:
    branch: main
  access_key_id: $AwsAccessKey
  secret_access_key: $AwsSecretAccessKey