FROM node:alpine
RUN cd usr \
    && mkdir src \
    && cd src \
    && mkdir app
RUN chmod -R 777 /usr/src/app

WORKDIR /usr/src/app

COPY react-docker/package.json ./

RUN npm install
COPY react-docker/ ./
EXPOSE 80
CMD ["npm","start"]